'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="GEOSYS")>  _
Partial Public Class ThorDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.mtEnvioReportesGEO.My.MySettings.Default.GEOSYSConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.spEtiquetasConsultar")>  _
	Public Function spEtiquetasConsultar(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdDispositivo", DbType:="VarChar(20)")> ByVal idDispositivo As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Intervalo", DbType:="VarChar(3)")> ByVal intervalo As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="FechaInicial", DbType:="VarChar(20)")> ByVal fechaInicial As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="FechaFinal", DbType:="VarChar(20)")> ByVal fechaFinal As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdUsuario", DbType:="Int")> ByVal idUsuario As System.Nullable(Of Integer)) As ISingleResult(Of spEtiquetasConsultarResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idDispositivo, intervalo, fechaInicial, fechaFinal, idUsuario)
		Return CType(result.ReturnValue,ISingleResult(Of spEtiquetasConsultarResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.spReporteProgramadoListar")>  _
	Public Function spReporteProgramadoListar(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal idUsuario As System.Nullable(Of Integer)) As ISingleResult(Of spReporteProgramadoListarResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idUsuario)
		Return CType(result.ReturnValue,ISingleResult(Of spReporteProgramadoListarResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.spReporteProgramadoListaActualizar")>  _
	Public Function spReporteProgramadoListaActualizar(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Secuencia", DbType:="Int")> ByVal secuencia As System.Nullable(Of Integer)) As Integer
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), secuencia)
		Return CType(result.ReturnValue,Integer)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.GetVIDPlaca", IsComposable:=true)>  _
	Public Function GetVIDPlaca(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Alias", DbType:="VarChar(30)")> ByVal [alias] As String) As String
		Return CType(Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), [alias]).ReturnValue,String)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.spActivosSinReportar")>  _
	Public Function spActivosSinReportar(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IdUsuario", DbType:="Int")> ByVal idUsuario As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="IP", DbType:="VarChar(20)")> ByVal iP As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="VID", DbType:="VarChar(30)")> ByVal vID As String) As ISingleResult(Of spActivosSinReportarResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idUsuario, iP, vID)
		Return CType(result.ReturnValue,ISingleResult(Of spActivosSinReportarResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.spDispositivoPermanencia")>  _
	Public Function spDispositivoPermanencia(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="VarChar(40)")> ByVal vid As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Desde", DbType:="VarChar(20)")> ByVal desde As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Hasta", DbType:="VarChar(20)")> ByVal hasta As String) As ISingleResult(Of spDispositivoPermanenciaResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), vid, desde, hasta)
		Return CType(result.ReturnValue,ISingleResult(Of spDispositivoPermanenciaResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.Minute2Text", IsComposable:=true)>  _
	Public Function Minute2Text(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="CantidadMinutos", DbType:="Float")> ByVal cantidadMinutos As System.Nullable(Of Double)) As String
		Return CType(Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), cantidadMinutos).ReturnValue,String)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.Minute2Text2", IsComposable:=true)>  _
	Public Function Minute2Text2(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="CantidadMinutos", DbType:="Float")> ByVal cantidadMinutos As System.Nullable(Of Double)) As String
		Return CType(Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), cantidadMinutos).ReturnValue,String)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.getUsuarioxID", IsComposable:=true)>  _
	Public Function getUsuarioxID(<Global.System.Data.Linq.Mapping.ParameterAttribute(DbType:="Int")> ByVal idUsuario As System.Nullable(Of Integer)) As String
		Return CType(Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), idUsuario).ReturnValue,String)
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.spActivoAliasBuscar")>  _
	Public Function spActivoAliasBuscar(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Vid", DbType:="VarChar(20)")> ByVal vid As String) As ISingleResult(Of spActivoAliasBuscarResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), vid)
		Return CType(result.ReturnValue,ISingleResult(Of spActivoAliasBuscarResult))
	End Function
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.getDescripcionEvento", IsComposable:=true)>  _
	Public Function getDescripcionEvento(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Vid", DbType:="VarChar(30)")> ByVal vid As String, <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="Evento", DbType:="Int")> ByVal evento As System.Nullable(Of Integer)) As String
		Return CType(Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), vid, evento).ReturnValue,String)
	End Function
End Class

Partial Public Class spEtiquetasConsultarResult
	
	Private _Etiqueta As String
	
	Private _FechaInicio As Date
	
	Private _FechaHasta As System.Nullable(Of Date)
	
	Private _Actual As Boolean
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Etiqueta", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property Etiqueta() As String
		Get
			Return Me._Etiqueta
		End Get
		Set
			If (String.Equals(Me._Etiqueta, value) = false) Then
				Me._Etiqueta = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FechaInicio", DbType:="DateTime NOT NULL")>  _
	Public Property FechaInicio() As Date
		Get
			Return Me._FechaInicio
		End Get
		Set
			If ((Me._FechaInicio = value)  _
						= false) Then
				Me._FechaInicio = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FechaHasta", DbType:="DateTime")>  _
	Public Property FechaHasta() As System.Nullable(Of Date)
		Get
			Return Me._FechaHasta
		End Get
		Set
			If (Me._FechaHasta.Equals(value) = false) Then
				Me._FechaHasta = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Actual", DbType:="Bit NOT NULL")>  _
	Public Property Actual() As Boolean
		Get
			Return Me._Actual
		End Get
		Set
			If ((Me._Actual = value)  _
						= false) Then
				Me._Actual = value
			End If
		End Set
	End Property
End Class

Partial Public Class spReporteProgramadoListarResult
	
	Private _IdUsuario As Integer
	
	Private _Email As String
	
	Private _HoraEnvio As String
	
	Private _TipoReporte As String
	
	Private _Intervalo As String
	
	Private _Parametros As String
	
	Private _Activos As String
	
	Private _Secuencia As Integer
	
	Private _Horas As System.Nullable(Of Integer)
	
	Private _Guardar As Boolean
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdUsuario", DbType:="Int NOT NULL")>  _
	Public Property IdUsuario() As Integer
		Get
			Return Me._IdUsuario
		End Get
		Set
			If ((Me._IdUsuario = value)  _
						= false) Then
				Me._IdUsuario = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Email", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property Email() As String
		Get
			Return Me._Email
		End Get
		Set
			If (String.Equals(Me._Email, value) = false) Then
				Me._Email = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HoraEnvio", DbType:="VarChar(30)")>  _
	Public Property HoraEnvio() As String
		Get
			Return Me._HoraEnvio
		End Get
		Set
			If (String.Equals(Me._HoraEnvio, value) = false) Then
				Me._HoraEnvio = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TipoReporte", DbType:="VarChar(200) NOT NULL", CanBeNull:=false)>  _
	Public Property TipoReporte() As String
		Get
			Return Me._TipoReporte
		End Get
		Set
			If (String.Equals(Me._TipoReporte, value) = false) Then
				Me._TipoReporte = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Intervalo", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property Intervalo() As String
		Get
			Return Me._Intervalo
		End Get
		Set
			If (String.Equals(Me._Intervalo, value) = false) Then
				Me._Intervalo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Parametros", DbType:="VarChar(100)")>  _
	Public Property Parametros() As String
		Get
			Return Me._Parametros
		End Get
		Set
			If (String.Equals(Me._Parametros, value) = false) Then
				Me._Parametros = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Activos", DbType:="VarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property Activos() As String
		Get
			Return Me._Activos
		End Get
		Set
			If (String.Equals(Me._Activos, value) = false) Then
				Me._Activos = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Secuencia", DbType:="Int NOT NULL")>  _
	Public Property Secuencia() As Integer
		Get
			Return Me._Secuencia
		End Get
		Set
			If ((Me._Secuencia = value)  _
						= false) Then
				Me._Secuencia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Horas", DbType:="Int")>  _
	Public Property Horas() As System.Nullable(Of Integer)
		Get
			Return Me._Horas
		End Get
		Set
			If (Me._Horas.Equals(value) = false) Then
				Me._Horas = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Guardar", DbType:="Bit NOT NULL")>  _
	Public Property Guardar() As Boolean
		Get
			Return Me._Guardar
		End Get
		Set
			If ((Me._Guardar = value)  _
						= false) Then
				Me._Guardar = value
			End If
		End Set
	End Property
End Class

Partial Public Class spActivosSinReportarResult
	
	Private _IdEntidad As String
	
	Private _Entidad As String
	
	Private _IdActivo As Integer
	
	Private _VID As String
	
	Private _Alias As String
	
	Private _Ignicion As String
	
	Private _Rumbo As String
	
	Private _Velocidad As String
	
	Private _Latitud As String
	
	Private _Longitud As String
	
	Private _Odometro As String
	
	Private _Calle As String
	
	Private _Pto__Cercano As String
	
	Private _UltimoReporte As System.Nullable(Of Date)
	
	Private _UltimoReporteServidor As System.Nullable(Of Date)
	
	Private _DiasSinReportar As String
	
	Private _Evento As System.Nullable(Of Integer)
	
	Private _DEvento As String
	
	Private _Marca As String
	
	Private _Modelo As String
	
	Private _Motor As String
	
	Private _Chasis As String
	
	Private _Color As String
	
	Private _Año As String
	
	Private _CodSysHunter As String
	
	Private _Producto As String
	
	Private _Icono As String
	
	Private _Actividad As String
	
	Private _IdUsuario As Integer
	
	Private _NivelBateria As String
	
	Private _VoltajeBateria As String
	
	Private _EstadoGPS As String
	
	Private _Horometro As String
	
	Private _VoltajeAlimentacion As String
	
	Private _EA1 As String
	
	Private _EA2 As String
	
	Private _EA3 As String
	
	Private _SA1 As String
	
	Private _SA2 As String
	
	Private _SA3 As String
	
	Private _DriverID As String
	
	Private _IdChofer As String
	
	Private _Chofer As String
	
	Private _ChoferDriverID As String
	
	Private _Estado As String
	
	Private _VelocidadOBD As String
	
	Private _rpmOBD As String
	
	Private _PosicionAceleradorOBD As String
	
	Private _OdometroOBD As String
	
	Private _OdometroViajeOBD As String
	
	Private _NivelGasolinaOBD As String
	
	Private _CombustibleRestanteOBD As String
	
	Private _EngraneTransmisionOBD As String
	
	Private _TemperaturaRefrigeranteOBD As String
	
	Private _IndiceGasolinaOBD As String
	
	Private _VoltajeAlimentacionOBD As String
	
	Private _EstadoSeñalesGiroOBD As String
	
	Private _GasolinaConsumidaPorViajeOBD As String
	
	Private _IndicadoresOBD As String
	
	Private _CE As String
	
	Private _TipoVehiculo As String
	
	Private _Provincia As String
	
	Private _DetenidoDesde As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdEntidad", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property IdEntidad() As String
		Get
			Return Me._IdEntidad
		End Get
		Set
			If (String.Equals(Me._IdEntidad, value) = false) Then
				Me._IdEntidad = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Entidad", DbType:="VarChar(201)")>  _
	Public Property Entidad() As String
		Get
			Return Me._Entidad
		End Get
		Set
			If (String.Equals(Me._Entidad, value) = false) Then
				Me._Entidad = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdActivo", DbType:="Int NOT NULL")>  _
	Public Property IdActivo() As Integer
		Get
			Return Me._IdActivo
		End Get
		Set
			If ((Me._IdActivo = value)  _
						= false) Then
				Me._IdActivo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VID", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property VID() As String
		Get
			Return Me._VID
		End Get
		Set
			If (String.Equals(Me._VID, value) = false) Then
				Me._VID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="Alias", Storage:="_Alias", DbType:="VarChar(8000)")>  _
	Public Property [Alias]() As String
		Get
			Return Me._Alias
		End Get
		Set
			If (String.Equals(Me._Alias, value) = false) Then
				Me._Alias = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Ignicion", DbType:="VarChar(30)")>  _
	Public Property Ignicion() As String
		Get
			Return Me._Ignicion
		End Get
		Set
			If (String.Equals(Me._Ignicion, value) = false) Then
				Me._Ignicion = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Rumbo", DbType:="VarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property Rumbo() As String
		Get
			Return Me._Rumbo
		End Get
		Set
			If (String.Equals(Me._Rumbo, value) = false) Then
				Me._Rumbo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Velocidad", DbType:="VarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property Velocidad() As String
		Get
			Return Me._Velocidad
		End Get
		Set
			If (String.Equals(Me._Velocidad, value) = false) Then
				Me._Velocidad = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Latitud", DbType:="VarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property Latitud() As String
		Get
			Return Me._Latitud
		End Get
		Set
			If (String.Equals(Me._Latitud, value) = false) Then
				Me._Latitud = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Longitud", DbType:="VarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property Longitud() As String
		Get
			Return Me._Longitud
		End Get
		Set
			If (String.Equals(Me._Longitud, value) = false) Then
				Me._Longitud = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Odometro", DbType:="VarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property Odometro() As String
		Get
			Return Me._Odometro
		End Get
		Set
			If (String.Equals(Me._Odometro, value) = false) Then
				Me._Odometro = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Calle", DbType:="VarChar(300)")>  _
	Public Property Calle() As String
		Get
			Return Me._Calle
		End Get
		Set
			If (String.Equals(Me._Calle, value) = false) Then
				Me._Calle = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[Pto. Cercano]", Storage:="_Pto__Cercano", DbType:="VarChar(250)")>  _
	Public Property Pto__Cercano() As String
		Get
			Return Me._Pto__Cercano
		End Get
		Set
			If (String.Equals(Me._Pto__Cercano, value) = false) Then
				Me._Pto__Cercano = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UltimoReporte", DbType:="DateTime")>  _
	Public Property UltimoReporte() As System.Nullable(Of Date)
		Get
			Return Me._UltimoReporte
		End Get
		Set
			If (Me._UltimoReporte.Equals(value) = false) Then
				Me._UltimoReporte = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UltimoReporteServidor", DbType:="DateTime")>  _
	Public Property UltimoReporteServidor() As System.Nullable(Of Date)
		Get
			Return Me._UltimoReporteServidor
		End Get
		Set
			If (Me._UltimoReporteServidor.Equals(value) = false) Then
				Me._UltimoReporteServidor = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DiasSinReportar", DbType:="VarChar(37)")>  _
	Public Property DiasSinReportar() As String
		Get
			Return Me._DiasSinReportar
		End Get
		Set
			If (String.Equals(Me._DiasSinReportar, value) = false) Then
				Me._DiasSinReportar = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Evento", DbType:="Int")>  _
	Public Property Evento() As System.Nullable(Of Integer)
		Get
			Return Me._Evento
		End Get
		Set
			If (Me._Evento.Equals(value) = false) Then
				Me._Evento = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DEvento", DbType:="VarChar(100)")>  _
	Public Property DEvento() As String
		Get
			Return Me._DEvento
		End Get
		Set
			If (String.Equals(Me._DEvento, value) = false) Then
				Me._DEvento = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Marca", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property Marca() As String
		Get
			Return Me._Marca
		End Get
		Set
			If (String.Equals(Me._Marca, value) = false) Then
				Me._Marca = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Modelo", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
	Public Property Modelo() As String
		Get
			Return Me._Modelo
		End Get
		Set
			If (String.Equals(Me._Modelo, value) = false) Then
				Me._Modelo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Motor", DbType:="VarChar(50)")>  _
	Public Property Motor() As String
		Get
			Return Me._Motor
		End Get
		Set
			If (String.Equals(Me._Motor, value) = false) Then
				Me._Motor = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Chasis", DbType:="VarChar(50)")>  _
	Public Property Chasis() As String
		Get
			Return Me._Chasis
		End Get
		Set
			If (String.Equals(Me._Chasis, value) = false) Then
				Me._Chasis = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Color", DbType:="VarChar(20)")>  _
	Public Property Color() As String
		Get
			Return Me._Color
		End Get
		Set
			If (String.Equals(Me._Color, value) = false) Then
				Me._Color = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Año", DbType:="VarChar(4)")>  _
	Public Property Año() As String
		Get
			Return Me._Año
		End Get
		Set
			If (String.Equals(Me._Año, value) = false) Then
				Me._Año = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CodSysHunter", DbType:="VarChar(50)")>  _
	Public Property CodSysHunter() As String
		Get
			Return Me._CodSysHunter
		End Get
		Set
			If (String.Equals(Me._CodSysHunter, value) = false) Then
				Me._CodSysHunter = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Producto", DbType:="VarChar(50)")>  _
	Public Property Producto() As String
		Get
			Return Me._Producto
		End Get
		Set
			If (String.Equals(Me._Producto, value) = false) Then
				Me._Producto = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Icono", DbType:="VarChar(500) NOT NULL", CanBeNull:=false)>  _
	Public Property Icono() As String
		Get
			Return Me._Icono
		End Get
		Set
			If (String.Equals(Me._Icono, value) = false) Then
				Me._Icono = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Actividad", DbType:="VarChar(500) NOT NULL", CanBeNull:=false)>  _
	Public Property Actividad() As String
		Get
			Return Me._Actividad
		End Get
		Set
			If (String.Equals(Me._Actividad, value) = false) Then
				Me._Actividad = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdUsuario", DbType:="Int NOT NULL")>  _
	Public Property IdUsuario() As Integer
		Get
			Return Me._IdUsuario
		End Get
		Set
			If ((Me._IdUsuario = value)  _
						= false) Then
				Me._IdUsuario = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NivelBateria", DbType:="VarChar(30)")>  _
	Public Property NivelBateria() As String
		Get
			Return Me._NivelBateria
		End Get
		Set
			If (String.Equals(Me._NivelBateria, value) = false) Then
				Me._NivelBateria = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VoltajeBateria", DbType:="VarChar(30)")>  _
	Public Property VoltajeBateria() As String
		Get
			Return Me._VoltajeBateria
		End Get
		Set
			If (String.Equals(Me._VoltajeBateria, value) = false) Then
				Me._VoltajeBateria = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EstadoGPS", DbType:="VarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property EstadoGPS() As String
		Get
			Return Me._EstadoGPS
		End Get
		Set
			If (String.Equals(Me._EstadoGPS, value) = false) Then
				Me._EstadoGPS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Horometro", DbType:="VarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property Horometro() As String
		Get
			Return Me._Horometro
		End Get
		Set
			If (String.Equals(Me._Horometro, value) = false) Then
				Me._Horometro = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VoltajeAlimentacion", DbType:="VarChar(30)")>  _
	Public Property VoltajeAlimentacion() As String
		Get
			Return Me._VoltajeAlimentacion
		End Get
		Set
			If (String.Equals(Me._VoltajeAlimentacion, value) = false) Then
				Me._VoltajeAlimentacion = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EA1", DbType:="VarChar(30)")>  _
	Public Property EA1() As String
		Get
			Return Me._EA1
		End Get
		Set
			If (String.Equals(Me._EA1, value) = false) Then
				Me._EA1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EA2", DbType:="VarChar(30)")>  _
	Public Property EA2() As String
		Get
			Return Me._EA2
		End Get
		Set
			If (String.Equals(Me._EA2, value) = false) Then
				Me._EA2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EA3", DbType:="VarChar(30)")>  _
	Public Property EA3() As String
		Get
			Return Me._EA3
		End Get
		Set
			If (String.Equals(Me._EA3, value) = false) Then
				Me._EA3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SA1", DbType:="VarChar(30)")>  _
	Public Property SA1() As String
		Get
			Return Me._SA1
		End Get
		Set
			If (String.Equals(Me._SA1, value) = false) Then
				Me._SA1 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SA2", DbType:="VarChar(30)")>  _
	Public Property SA2() As String
		Get
			Return Me._SA2
		End Get
		Set
			If (String.Equals(Me._SA2, value) = false) Then
				Me._SA2 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SA3", DbType:="VarChar(30)")>  _
	Public Property SA3() As String
		Get
			Return Me._SA3
		End Get
		Set
			If (String.Equals(Me._SA3, value) = false) Then
				Me._SA3 = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DriverID", DbType:="VarChar(30)")>  _
	Public Property DriverID() As String
		Get
			Return Me._DriverID
		End Get
		Set
			If (String.Equals(Me._DriverID, value) = false) Then
				Me._DriverID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdChofer", DbType:="VarChar(30)")>  _
	Public Property IdChofer() As String
		Get
			Return Me._IdChofer
		End Get
		Set
			If (String.Equals(Me._IdChofer, value) = false) Then
				Me._IdChofer = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Chofer", DbType:="VarChar(301)")>  _
	Public Property Chofer() As String
		Get
			Return Me._Chofer
		End Get
		Set
			If (String.Equals(Me._Chofer, value) = false) Then
				Me._Chofer = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ChoferDriverID", DbType:="VarChar(301)")>  _
	Public Property ChoferDriverID() As String
		Get
			Return Me._ChoferDriverID
		End Get
		Set
			If (String.Equals(Me._ChoferDriverID, value) = false) Then
				Me._ChoferDriverID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Estado", DbType:="VarChar(3)")>  _
	Public Property Estado() As String
		Get
			Return Me._Estado
		End Get
		Set
			If (String.Equals(Me._Estado, value) = false) Then
				Me._Estado = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VelocidadOBD", DbType:="VarChar(30)")>  _
	Public Property VelocidadOBD() As String
		Get
			Return Me._VelocidadOBD
		End Get
		Set
			If (String.Equals(Me._VelocidadOBD, value) = false) Then
				Me._VelocidadOBD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_rpmOBD", DbType:="VarChar(30)")>  _
	Public Property rpmOBD() As String
		Get
			Return Me._rpmOBD
		End Get
		Set
			If (String.Equals(Me._rpmOBD, value) = false) Then
				Me._rpmOBD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PosicionAceleradorOBD", DbType:="VarChar(30)")>  _
	Public Property PosicionAceleradorOBD() As String
		Get
			Return Me._PosicionAceleradorOBD
		End Get
		Set
			If (String.Equals(Me._PosicionAceleradorOBD, value) = false) Then
				Me._PosicionAceleradorOBD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OdometroOBD", DbType:="VarChar(30)")>  _
	Public Property OdometroOBD() As String
		Get
			Return Me._OdometroOBD
		End Get
		Set
			If (String.Equals(Me._OdometroOBD, value) = false) Then
				Me._OdometroOBD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OdometroViajeOBD", DbType:="VarChar(30)")>  _
	Public Property OdometroViajeOBD() As String
		Get
			Return Me._OdometroViajeOBD
		End Get
		Set
			If (String.Equals(Me._OdometroViajeOBD, value) = false) Then
				Me._OdometroViajeOBD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NivelGasolinaOBD", DbType:="VarChar(30)")>  _
	Public Property NivelGasolinaOBD() As String
		Get
			Return Me._NivelGasolinaOBD
		End Get
		Set
			If (String.Equals(Me._NivelGasolinaOBD, value) = false) Then
				Me._NivelGasolinaOBD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CombustibleRestanteOBD", DbType:="VarChar(30)")>  _
	Public Property CombustibleRestanteOBD() As String
		Get
			Return Me._CombustibleRestanteOBD
		End Get
		Set
			If (String.Equals(Me._CombustibleRestanteOBD, value) = false) Then
				Me._CombustibleRestanteOBD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EngraneTransmisionOBD", DbType:="VarChar(30)")>  _
	Public Property EngraneTransmisionOBD() As String
		Get
			Return Me._EngraneTransmisionOBD
		End Get
		Set
			If (String.Equals(Me._EngraneTransmisionOBD, value) = false) Then
				Me._EngraneTransmisionOBD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TemperaturaRefrigeranteOBD", DbType:="VarChar(30)")>  _
	Public Property TemperaturaRefrigeranteOBD() As String
		Get
			Return Me._TemperaturaRefrigeranteOBD
		End Get
		Set
			If (String.Equals(Me._TemperaturaRefrigeranteOBD, value) = false) Then
				Me._TemperaturaRefrigeranteOBD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IndiceGasolinaOBD", DbType:="VarChar(30)")>  _
	Public Property IndiceGasolinaOBD() As String
		Get
			Return Me._IndiceGasolinaOBD
		End Get
		Set
			If (String.Equals(Me._IndiceGasolinaOBD, value) = false) Then
				Me._IndiceGasolinaOBD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VoltajeAlimentacionOBD", DbType:="VarChar(30)")>  _
	Public Property VoltajeAlimentacionOBD() As String
		Get
			Return Me._VoltajeAlimentacionOBD
		End Get
		Set
			If (String.Equals(Me._VoltajeAlimentacionOBD, value) = false) Then
				Me._VoltajeAlimentacionOBD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EstadoSeñalesGiroOBD", DbType:="VarChar(30)")>  _
	Public Property EstadoSeñalesGiroOBD() As String
		Get
			Return Me._EstadoSeñalesGiroOBD
		End Get
		Set
			If (String.Equals(Me._EstadoSeñalesGiroOBD, value) = false) Then
				Me._EstadoSeñalesGiroOBD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GasolinaConsumidaPorViajeOBD", DbType:="VarChar(30)")>  _
	Public Property GasolinaConsumidaPorViajeOBD() As String
		Get
			Return Me._GasolinaConsumidaPorViajeOBD
		End Get
		Set
			If (String.Equals(Me._GasolinaConsumidaPorViajeOBD, value) = false) Then
				Me._GasolinaConsumidaPorViajeOBD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IndicadoresOBD", DbType:="VarChar(30)")>  _
	Public Property IndicadoresOBD() As String
		Get
			Return Me._IndicadoresOBD
		End Get
		Set
			If (String.Equals(Me._IndicadoresOBD, value) = false) Then
				Me._IndicadoresOBD = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CE", DbType:="VarChar(30)")>  _
	Public Property CE() As String
		Get
			Return Me._CE
		End Get
		Set
			If (String.Equals(Me._CE, value) = false) Then
				Me._CE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TipoVehiculo", DbType:="VarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property TipoVehiculo() As String
		Get
			Return Me._TipoVehiculo
		End Get
		Set
			If (String.Equals(Me._TipoVehiculo, value) = false) Then
				Me._TipoVehiculo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Provincia", DbType:="VarChar(MAX)")>  _
	Public Property Provincia() As String
		Get
			Return Me._Provincia
		End Get
		Set
			If (String.Equals(Me._Provincia, value) = false) Then
				Me._Provincia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DetenidoDesde", DbType:="VarChar(40)")>  _
	Public Property DetenidoDesde() As String
		Get
			Return Me._DetenidoDesde
		End Get
		Set
			If (String.Equals(Me._DetenidoDesde, value) = false) Then
				Me._DetenidoDesde = value
			End If
		End Set
	End Property
End Class

Partial Public Class spDispositivoPermanenciaResult
	
	Private _Permanencia As System.Nullable(Of Double)
	
	Private _Direccion As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Permanencia", DbType:="Float")>  _
	Public Property Permanencia() As System.Nullable(Of Double)
		Get
			Return Me._Permanencia
		End Get
		Set
			If (Me._Permanencia.Equals(value) = false) Then
				Me._Permanencia = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Direccion", DbType:="VarChar(300)")>  _
	Public Property Direccion() As String
		Get
			Return Me._Direccion
		End Get
		Set
			If (String.Equals(Me._Direccion, value) = false) Then
				Me._Direccion = value
			End If
		End Set
	End Property
End Class

Partial Public Class spActivoAliasBuscarResult
	
	Private _Alias As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="Alias", Storage:="_Alias", DbType:="VarChar(50)")>  _
	Public Property [Alias]() As String
		Get
			Return Me._Alias
		End Get
		Set
			If (String.Equals(Me._Alias, value) = false) Then
				Me._Alias = value
			End If
		End Set
	End Property
End Class
