'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ddulanto")>  _
        Public ReadOnly Property UsuarioEmail() As String
            Get
                Return CType(Me("UsuarioEmail"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ddulanto")>  _
        Public ReadOnly Property ClaveEmail() As String
            Get
                Return CType(Me("ClaveEmail"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public ReadOnly Property GenerarMaps() As Boolean
            Get
                Return CType(Me("GenerarMaps"),Boolean)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("AÑO;MES;DIA;KMS;CONSUMO;EXCESO100;FRENADA;GIROIZQ;GIRODER;RALENTI;ALARMA")>  _
        Public ReadOnly Property ColumnasReporte() As String
            Get
                Return CType(Me("ColumnasReporte"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public ReadOnly Property UsarTablaCalificacion() As Boolean
            Get
                Return CType(Me("UsarTablaCalificacion"),Boolean)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60000")>  _
        Public ReadOnly Property Espera() As Integer
            Get
                Return CType(Me("Espera"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public ReadOnly Property Debug() As UInteger
            Get
                Return CType(Me("Debug"),UInteger)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public ReadOnly Property EnviarEmails() As Boolean
            Get
                Return CType(Me("EnviarEmails"),Boolean)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\inetpub\wwwroot\Geo\Reportes\Descargas\")>  _
        Public ReadOnly Property RutaDescargas() As String
            Get
                Return CType(Me("RutaDescargas"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7200000")>  _
        Public ReadOnly Property EsperaLoadData() As Integer
            Get
                Return CType(Me("EsperaLoadData"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("informes@huntermonitoreoperu.com")>  _
        Public ReadOnly Property EmailDesde() As String
            Get
                Return CType(Me("EmailDesde"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("172.16.1.61")>  _
        Public ReadOnly Property ServidorEmail() As String
            Get
                Return CType(Me("ServidorEmail"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Autosafe")>  _
        Public ReadOnly Property Company() As String
            Get
                Return CType(Me("Company"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("00:00:00")>  _
        Public ReadOnly Property HoraInicio() As String
            Get
                Return CType(Me("HoraInicio"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("23:59:59")>  _
        Public ReadOnly Property HoraFin() As String
            Get
                Return CType(Me("HoraFin"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://172.16.1.81/reporte_icaro/PDF/genera_html.php?")>  _
        Public ReadOnly Property Url_GeneraHTML() As String
            Get
                Return CType(Me("Url_GeneraHTML"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://172.16.1.81/reporte_icaro/PDF/genera_pdf.php?")>  _
        Public ReadOnly Property Url_GeneraPDF() As String
            Get
                Return CType(Me("Url_GeneraPDF"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://172.16.1.81/download_ejecutivo/PDFS/")>  _
        Public ReadOnly Property Url_DownloadPDF() As String
            Get
                Return CType(Me("Url_DownloadPDF"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://172.16.1.81/download_ejecutivo/HTML/")>  _
        Public ReadOnly Property Url_DownloadHTML() As String
            Get
                Return CType(Me("Url_DownloadHTML"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public ReadOnly Property ReporteProgramadoPendiente_GuardarLog() As String
            Get
                Return CType(Me("ReporteProgramadoPendiente_GuardarLog"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PE")>  _
        Public ReadOnly Property Pais() As String
            Get
                Return CType(Me("Pais"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000000")>  _
        Public ReadOnly Property TotalRegistrosMaximo() As String
            Get
                Return CType(Me("TotalRegistrosMaximo"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.huntermonitoreoperu.com/GeoV3.3/images/LOGO_HUNTER_PARA_PLATAFORMA.png"& _ 
            "")>  _
        Public ReadOnly Property ImagenCabeceraEmail() As String
            Get
                Return CType(Me("ImagenCabeceraEmail"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Basic YTQ0MjM1OGQ4MTY3NDc4ZTgzYmIzMjc1ZmY2MDQxNDI=")>  _
        Public ReadOnly Property TokenEmBlue() As String
            Get
                Return CType(Me("TokenEmBlue"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://track.embluemail.com/contacts/event")>  _
        Public ReadOnly Property Url_EmBlueOne() As String
            Get
                Return CType(Me("Url_EmBlueOne"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://track.embluemail.com/contacts/event/bulk")>  _
        Public ReadOnly Property Url_EmBlueBulk() As String
            Get
                Return CType(Me("Url_EmBlueBulk"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=191.98.146.190,47000;Initial Catalog=GEOSYS;User ID=userBDIcaro;Passw"& _ 
            "ord=userBDIcaro;Max Pool Size=10024")>  _
        Public ReadOnly Property GEOSYSConnectionStringMain() As String
            Get
                Return CType(Me("GEOSYSConnectionStringMain"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=191.98.146.190,47000;Initial Catalog=GEOSYS;User ID=userBDIcaro;Passw"& _ 
            "ord=userBDIcaro;Max Pool Size=10024")>  _
        Public ReadOnly Property GEOSYSConnectionStringAux() As String
            Get
                Return CType(Me("GEOSYSConnectionStringAux"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Basic YTQ0MjM1OGQ4MTY3NDc4ZTgzYmIzMjc1ZmY2MDQxNDI=")>  _
        Public ReadOnly Property TokenHunter() As String
            Get
                Return CType(Me("TokenHunter"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.huntermonitoreoperu.com:3333/api.integracion/v1/email")>  _
        Public ReadOnly Property UrlApiHunter() As String
            Get
                Return CType(Me("UrlApiHunter"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Icaro.My.MySettings
            Get
                Return Global.Icaro.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
